name: clamp3
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.7.2=haa95532_0
  - cuda-cccl=12.6.37=0
  - cuda-cccl_win-64=12.6.37=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.6.68=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - freetype=2.12.1=ha860e81_0
  - gmpy2=2.1.2=py310h7f96b67_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.4=py310haa95532_0
  - jpeg=9e=h827c3e9_3
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.7.68=0
  - libcurand-dev=10.3.7.68=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.8=py310h2bbff1b_0
  - mkl_random=1.2.4=py310h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py310haa95532_0
  - networkx=3.3=py310haa95532_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.14=h827c3e9_0
  - pip=24.2=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.14=he1021f5_1
  - pytorch=2.4.0=py3.10_cuda11.8_cudnn9_0
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h2bbff1b_0
  - requests=2.32.3=py310haa95532_0
  - setuptools=72.1.0=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - sympy=1.13.2=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - typing_extensions=4.11.0=py310haa95532_0
  - tzdata=2024a=h04d1e81_0
  - vc=14.40=h2eaa2aa_0
  - vs2015_runtime=14.40.33807=h98bb1dd_0
  - wheel=0.43.0=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.5=hd43e919_2
  - pip:
      - abctoolkit==0.0.4
      - accelerate==0.34.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - audioread==3.0.1
      - certifi==2023.7.22
      - cffi==1.17.0
      - chardet==5.2.0
      - charset-normalizer==3.2.0
      - click==8.1.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - cycler==0.11.0
      - datasets==2.21.0
      - decorator==5.1.1
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.2
      - filelock==3.12.2
      - fonttools==4.38.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.24.6
      - humanfriendly==10.0
      - idna==3.4
      - importlib-metadata==6.7.0
      - jellyfish==1.0.0
      - jiter==0.6.1
      - joblib==1.3.2
      - jsonpickle==3.0.2
      - kiwisolver==1.4.4
      - langcodes==3.4.0
      - langdetect==1.0.9
      - langid==1.1.6
      - language-data==1.2.0
      - lazy-loader==0.4
      - levenshtein==0.25.1
      - librosa==0.10.1
      - llvmlite==0.43.0
      - lxml==5.3.0
      - marisa-trie==1.2.0
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - mido==1.3.0
      - more-itertools==9.1.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - music21==7.3.3
      - nltk==3.8.1
      - numba==0.60.0
      - openai==1.51.2
      - optimum==1.21.4
      - packaging==23.1
      - pandas==1.3.5
      - pillow==9.5.0
      - platformdirs==4.2.2
      - pooch==1.8.2
      - portalocker==2.10.1
      - protobuf==5.28.0
      - psutil==6.0.0
      - pyarrow==17.0.0
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pyparsing==3.1.1
      - pyreadline3==3.4.1
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pywin32==306
      - rapidfuzz==3.9.7
      - rarfile==4.1
      - regex==2023.8.8
      - sacrebleu==2.4.3
      - sacremoses==0.0.53
      - safetensors==0.4.4
      - samplings==0.1.7
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==2.4.0
      - torchaudio==2.4.0
      - torchvision==0.19.0
      - tqdm==4.66.5
      - transformers==4.40.0
      - typing-extensions==4.12.2
      - unidecode==1.3.6
      - urllib3==2.0.4
      - wandb==0.17.8
      - webcolors==1.13
      - xxhash==3.5.0
      - yarl==1.9.7
      - zipp==3.15.0